### ISSUE TITLE
Transmit Buffer Full

### ISSUE THREAD

**Issue by MichaelBMiner** [skpang/PiCAN-Python-examples#4]
Hello,

I am using the obdii_logger.py example, after a few seconds of running I am given an error 
`CAN Rx test
Bring up CAN0....
RTNETLINK answers: Device or resource busy
Ready
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "main_test.py", line 68, in can_tx_task
    bus.send(msg)
  File "/home/pi/.local/lib/python3.7/site-packages/can/interfaces/socketcan/socketcan.py", line 665, in send
    raise can.CanError("Transmit buffer full")
can.CanError: Transmit buffer full
`

Is there anything I can do about this? I ran the command `sudo ifconfig can0 txqueuelen 10000` but see little to no change.

**Comment by MichaelBMiner** [comment]
Is there a check to perform? Some way to ask if the buffer is full?

**Comment by JPP1234567** [comment]
Hi, did you find the solution?

**Comment by ke5eua** [comment]
Was a solution ever found for this. Mine crashes on count 12.
